#!/usr/bin/env bash
# Render ~/.openclaw/openclaw.json and ~/.openclaw/.env.
# Two endpoints: OpenRouter (course standard, if you have a key) and
# OpenRouter (your own key). The default model points at whichever endpoint
# preflight validated (or, before preflight has run, whichever key is present —
# OpenRouter preferred). Override with OPENCLAW_PROVIDER=litellm|openrouter.
# Usage: scripts/configure.sh [OPENROUTER_API_KEY]
#   Key is resolved as: $1  >  env vars  >  existing ~/.openclaw/.env
# Idempotent: safe to run as many times as you like.
set -euo pipefail

# ---- Settings (override via env if your model/endpoint differ) ----
# Default OpenRouter model slug (cheap open model for routine agent loops).
# Verify the current slug at https://openrouter.ai/models before the term.
OPENCLAW_MODEL="${OPENCLAW_MODEL:-google/gemini-3.7-flash}"
# OU AI Sandbox endpoint (no-cost alternative).
LITELLM_BASE_URL="${LITELLM_BASE_URL:-https://litellm.lib.ou.edu}"
# NOTE: ids must match what the gateway reports at /v1/models — for these
# models that's the literal strings below, spaces included.
#
# Course default is a large model on purpose. Small coder models cannot
# reliably run a multi-step tool-using task: instead of failing they tend to
# fabricate a result and report success. Qwen3 Coder 30B did exactly that on
# the Ship Day assignment — invented search results, skipped the deploy, and
# announced "Website Successfully Built!". It is kept only as a fallback for
# when the primary is unavailable.
LITELLM_MODEL="${LITELLM_MODEL:-Claude Sonnet 4.6}"
LITELLM_MODEL_NAME="${LITELLM_MODEL_NAME:-Claude Sonnet 4.6 (OU LiteLLM)}"
# Optional comma-separated fallback model ids, PER PROVIDER. Fallbacks are
# prefixed with the active provider, so a single shared list would produce
# nonsense like "openrouter/Qwen3 Coder 30B" for an OpenRouter student.
# Note the "-" rather than ":-": setting these to an empty string explicitly
# means "no fallback", while leaving them unset takes the course default.
LITELLM_MODEL_FALLBACKS="${LITELLM_MODEL_FALLBACKS-Qwen3 Coder 30B}"
OPENROUTER_MODEL_FALLBACKS="${OPENROUTER_MODEL_FALLBACKS-qwen/qwen3.7-flash}"
# Legacy single-list override. If set, it wins for whichever provider is
# active — kept so existing env-var overrides keep working.
OPENCLAW_MODEL_FALLBACKS="${OPENCLAW_MODEL_FALLBACKS:-}"
# -----------------------------------------------------------------

STATE_DIR="${HOME}/.openclaw"
CONFIG_FILE="${STATE_DIR}/openclaw.json"
ENV_FILE="${STATE_DIR}/.env"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE="${REPO_DIR}/config/openclaw.template.json5"
OR_PLACEHOLDER="sk-or-REPLACE_ME"
LL_PLACEHOLDER="sk-REPLACE_ME"

mkdir -p "${STATE_DIR}"

# Make 'openclaw' findable for the optional validation step below.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_env.sh"

# Resolve the OpenRouter key: explicit arg > env var > existing .env file.
OR_KEY="${1:-${OPENROUTER_API_KEY:-}}"
if [[ -z "${OR_KEY}" && -f "${ENV_FILE}" ]]; then
  OR_KEY="$(grep -E '^OPENROUTER_API_KEY=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
fi
[[ -z "${OR_KEY}" ]] && OR_KEY="${OR_PLACEHOLDER}"

# Optional OU LiteLLM (backup) key — env var > existing .env file > placeholder.
LL_KEY="${LITELLM_API_KEY:-}"
if [[ -z "${LL_KEY}" && -f "${ENV_FILE}" ]]; then
  LL_KEY="$(grep -E '^LITELLM_API_KEY=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
fi
[[ -z "${LL_KEY}" ]] && LL_KEY="${LL_PLACEHOLDER}"

# Resolve/persist a gateway client-auth token. Even on loopback the gateway
# authenticates clients (the TUI), so we keep a stable per-Codespace token.
GW_TOKEN=""
[[ -f "${ENV_FILE}" ]] && GW_TOKEN="$(grep -E '^OPENCLAW_GATEWAY_TOKEN=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
[[ -z "${GW_TOKEN}" ]] && GW_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-}"
[[ -z "${GW_TOKEN}" ]] && GW_TOKEN="$(openssl rand -hex 24 2>/dev/null || (head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'))"

# Write ~/.openclaw/.env (OpenClaw reads this as a global env fallback).
umask 077
{
  printf '# Auto-generated by openclaw-codespace-starter. Do NOT commit.\n'
  printf 'OPENROUTER_API_KEY=%s\n' "${OR_KEY}"
  printf 'LITELLM_API_KEY=%s\n' "${LL_KEY}"
  printf 'OPENCLAW_GATEWAY_TOKEN=%s\n' "${GW_TOKEN}"
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

# Which endpoint should the default model use?
# OPENCLAW_PROVIDER env > preflight's ~/.openclaw/.provider > key presence
# (OpenRouter preferred — it's the course standard).
PROVIDER="${OPENCLAW_PROVIDER:-}"
if [[ -z "${PROVIDER}" && -f "${STATE_DIR}/.provider" ]]; then
  PROVIDER="$(cat "${STATE_DIR}/.provider" 2>/dev/null || true)"
fi
if [[ -z "${PROVIDER}" ]]; then
  # Fall 2026: OpenRouter is the course standard; the OU AI Sandbox is the no-cost alternative.
  if [[ -n "${OR_KEY}" && "${OR_KEY}" != "${OR_PLACEHOLDER:-__none__}" ]]; then PROVIDER="openrouter"; else PROVIDER="litellm"; fi
fi

# Build the model block: chosen provider's primary + that provider's fallbacks.
if [[ "${PROVIDER}" == "litellm" ]]; then
  PRIMARY_SLUG="litellm/${LITELLM_MODEL}"
  FALLBACK_LIST="${LITELLM_MODEL_FALLBACKS}"
else
  PRIMARY_SLUG="openrouter/${OPENCLAW_MODEL}"
  FALLBACK_LIST="${OPENROUTER_MODEL_FALLBACKS}"
fi
# Legacy override wins if someone set it explicitly.
[[ -n "${OPENCLAW_MODEL_FALLBACKS}" ]] && FALLBACK_LIST="${OPENCLAW_MODEL_FALLBACKS}"

MODEL_BLOCK="{ primary: \"${PRIMARY_SLUG}\""
FALLBACK_DESC="none"
if [[ -n "${FALLBACK_LIST}" ]]; then
  fb=""; fb_desc=""
  IFS=',' read -ra _fbs <<< "${FALLBACK_LIST}"
  for f in "${_fbs[@]}"; do
    # Trim surrounding whitespace only — these ids contain spaces.
    f="${f#"${f%%[![:space:]]*}"}"; f="${f%"${f##*[![:space:]]}"}"
    [[ -z "${f}" ]] && continue
    # A fallback identical to the primary can never help.
    [[ "${PROVIDER}/${f}" == "${PRIMARY_SLUG}" ]] && continue
    fb="${fb:+${fb}, }\"${PROVIDER}/${f}\""
    fb_desc="${fb_desc:+${fb_desc}, }${PROVIDER}/${f}"
  done
  if [[ -n "${fb}" ]]; then
    MODEL_BLOCK="${MODEL_BLOCK}, fallbacks: [${fb}]"
    FALLBACK_DESC="${fb_desc}"
  fi
fi
MODEL_BLOCK="${MODEL_BLOCK} }"

# Declare every LiteLLM model the config can reference. The gateway resolves
# agents.defaults.model against this list, so a fallback that is not declared
# here simply will not work. Declared regardless of the active provider, so
# scripts/select-model.sh can switch to any of them without a re-render.
LITELLM_DECLARED="${LITELLM_MODEL}"
if [[ -n "${LITELLM_MODEL_FALLBACKS}" ]]; then
  IFS=',' read -ra _decl <<< "${LITELLM_MODEL_FALLBACKS}"
  for f in "${_decl[@]}"; do
    f="${f#"${f%%[![:space:]]*}"}"; f="${f%"${f##*[![:space:]]}"}"
    [[ -z "${f}" || "${f}" == "${LITELLM_MODEL}" ]] && continue
    LITELLM_DECLARED="${LITELLM_DECLARED},${f}"
  done
fi
LITELLM_MODELS_JSON=""
IFS=',' read -ra _mids <<< "${LITELLM_DECLARED}"
for mid in "${_mids[@]}"; do
  [[ -z "${mid}" ]] && continue
  if [[ "${mid}" == "${LITELLM_MODEL}" ]]; then mname="${LITELLM_MODEL_NAME}"; else mname="${mid} (OU LiteLLM)"; fi
  LITELLM_MODELS_JSON="${LITELLM_MODELS_JSON}          {
            id: \"${mid}\",
            name: \"${mname}\",
            // Adjust these to match the real model if needed.
            reasoning: false,
            input: [\"text\"],
            contextWindow: ${LITELLM_CONTEXT_WINDOW:-128000},
            maxTokens: ${LITELLM_MAX_TOKENS:-8192},
          },
"
done

# Render the config from the template. The models array is multi-line, so it
# goes in via a file read rather than a sed replacement string.
MODELS_TMP="$(mktemp)"
printf '%s' "${LITELLM_MODELS_JSON}" > "${MODELS_TMP}"
sed -e "s#@@BASE_URL@@#${LITELLM_BASE_URL}#g" \
    -e "s#@@MODEL_ID@@#${LITELLM_MODEL}#g" \
    -e "s#@@MODEL_NAME@@#${LITELLM_MODEL_NAME}#g" \
    -e "/@@LITELLM_MODELS@@/{r ${MODELS_TMP}
d
}" \
    -e "s#@@MODEL_BLOCK@@#${MODEL_BLOCK}#g" \
    "${TEMPLATE}" > "${CONFIG_FILE}"
rm -f "${MODELS_TMP}"

echo "Wrote ${CONFIG_FILE}"
echo "  primary:   ${PRIMARY_SLUG}"
echo "  fallbacks: ${FALLBACK_DESC}"
echo "  LiteLLM gateway: ${LITELLM_BASE_URL}"

if [[ "${OR_KEY}" == "${OR_PLACEHOLDER}" && "${LL_KEY}" == "${LL_PLACEHOLDER}" ]]; then
  echo "!! No endpoint key found — wrote placeholders."
  echo "   Provide your OU LiteLLM Sandbox key (issued by the course), or create your"
  echo "   own OpenRouter key at https://openrouter.ai (Settings → Keys). Then run"
  echo "   'bash scripts/set-key.sh' or set the matching Codespaces secret."
fi

# Best-effort validation if OpenClaw is already installed.
if command -v openclaw >/dev/null 2>&1; then
  openclaw config validate >/dev/null 2>&1 \
    && echo "Config validated OK." \
    || echo "(Heads up: 'openclaw config validate' reported issues — run 'openclaw doctor' to inspect.)"
fi
